[profile.default]
solc_version = "0.8.12"
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
  "@ensdomains/=node_modules/@ensdomains/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@rari-capital/=node_modules/@rari-capital/",
  "base64-sol/=node_modules/base64-sol/",
  "eth-gas-reporter/=node_modules/eth-gas-reporter/",
  "hardhat/=node_modules/hardhat/"
]

# See more config options https://github.com/gakonst/foundry/tree/master/config